import Head from 'next/head';
// import BannerHome from './Banner';
import styles from './home.module.css';
import BannerHome from './Banner';
import {Typography, Box, Button} from '@mui/material';
import Layout from 'components/layout/Layout';
import {useSpring, useTransition, animated, config} from 'react-spring';
import AppFadeIn from '@crema/core/AnimateView/AppFadeIn';
import AppFadeInLeft from '@crema/core/AnimateView/AppFadeInLeft';
import Image from 'next/image';

export default function HomePage() {
  const opacityProps = useSpring({
    config: config.molasses,
    delay: 4400,
    from: {opacity: 0},
    to: {opacity: 1},
  });
  return (
    <>
      <Layout>
        <Head>
          <title>Satu Platform | Home </title>
          <meta name='description' content='Generated by create next app' />
        </Head>
        <BannerHome></BannerHome>
        <Box
          sx={{marginTop: {xs: '30px', md: '50px'}}}
          id='boxHome_2'
          className={`${styles.sectionbox}`}
        >
          <div className='container '>
            <div className='row'>
              <div className='col-12 text-center'>
                <Typography
                  sx={{
                    color: '#696969',
                    fontSize: {
                      xs: '13px',
                      md: '20px',
                    },
                    fontFamily: 'Montserrat',
                    fontWeight: '600',
                  }}
                >
                  Apa yang dapat Anda lakukan dengan Satuplatform?
                </Typography>
              </div>
            </div>
            <Box
              sx={{marginTop: {xs: '30px', md: '50px'}}}
              className='row  text-center'
            >
              <div className='col-lg-4'>
                <Box sx={{display: {xs: 'none', md: 'block'}}}>
                  <img
                    src='/assets/images/home/certificate.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      marginTop: {xs: '10px', md: '20px'},
                    }}
                  >
                    Melakukan penilaian <br /> keberlanjutan bagi bisnis <br />
                    Anda dan jaringan suplai Anda
                  </Typography>
                </Box>
                <Box
                  sx={{
                    display: {xs: 'flex', md: 'none'},
                    padding: '0px 25px',
                    marginBottom: '20px',
                  }}
                >
                  <img
                    src='/assets/images/home/certificate.svg'
                    className='img-fluid'
                    style={{width: '100px'}}
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      display: 'flex',
                      alignItems: 'center',
                      textAlign: 'left',
                      marginTop: {xs: '10px', md: '20px'},
                      marginLeft: '10px',
                    }}
                  >
                    Melakukan penilaian <br /> keberlanjutan bagi bisnis <br />
                    Anda dan jaringan suplai Anda
                  </Typography>
                </Box>
              </div>
              <div className='col-lg-4'>
                <Box
                  sx={{
                    display: {xs: 'flex', md: 'none'},
                    padding: '0px 25px',
                    marginBottom: '20px',
                  }}
                >
                  <img
                    src='/assets/images/home/pernilaian.svg'
                    className='img-fluid'
                    style={{width: '100px'}}
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      textAlign: 'left',
                      display: 'flex',
                      alignItems: 'center',
                      marginLeft: '10px',
                      marginTop: {xs: '10px', md: '20px'},
                    }}
                  >
                    Menganalisa kekurangan dan <br />
                    kelemahan bisnis Anda serta
                    <br /> dapatkan rencana tindakan perbaikan
                  </Typography>
                </Box>
                <Box sx={{display: {xs: 'none', md: 'block'}}}>
                  <img
                    src='/assets/images/home/pernilaian.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      marginTop: {xs: '10px', md: '20px'},
                    }}
                  >
                    Menganalisa kekurangan dan <br />
                    kelemahan bisnis Anda serta
                    <br /> dapatkan rencana tindakan perbaikan
                  </Typography>
                </Box>
              </div>
              <div className='col-lg-4'>
                <Box
                  sx={{
                    display: {xs: 'flex', md: 'none'},
                    padding: '0px 25px',
                  }}
                >
                  <img
                    src='/assets/images/home/report.svg'
                    className='img-fluid'
                    style={{width: '100px'}}
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      textAlign: 'left',
                      display: 'flex',
                      alignItems: 'center',
                      marginTop: {xs: '10px', md: '20px'},
                      marginLeft: '10px',
                    }}
                  >
                    Mempermudah manajemen <br />
                    audit lingkungan
                  </Typography>
                </Box>
                <Box sx={{display: {xs: 'none', md: 'block'}}}>
                  <img
                    src='/assets/images/home/report.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: '#4b4b4c',
                      fontWeight: '400',
                      lineHeight: '17px',
                      marginTop: {xs: '10px', md: '20px'},
                    }}
                  >
                    Mempermudah manajemen <br />
                    audit lingkungan
                  </Typography>
                </Box>
              </div>
            </Box>
          </div>
        </Box>
        {/* =================================== */}
        {/* <AppFadeIn> */}
        <section id='boxHomeMedal' className={` ${styles.sectionbox}`}>
          <Box
            sx={{
              backgroundColor: '#EDFFF4',
              width: '100%',
              paddingTop: {xs: '20px', md: '50px'},
              paddingBottom: '50px',
              marginTop: '60px',
            }}
          >
            <div className='container  '>
              <div className='row'>
                <div className='col-12 text-center'>
                  <Typography
                    sx={{
                      color: '#696969',
                      fontSize: {
                        xs: '13px',
                        md: '20px',
                      },
                      lineHeight: {xs: '21px', md: '25px'},
                      fontFamily: 'Montserrat',
                      fontWeight: '600',
                    }}
                  >
                    Dapatkan Label Ramah Lingkungan untuk Bisnis Anda
                  </Typography>
                </div>
              </div>
              <div className='row  mt-3 mt-md-5 text-center '>
                <div className='col-4'>
                  <img
                    src='/assets/images/home/goldmedal.svg'
                    className='img-fluid'
                  />
                </div>
                <div className='col-4'>
                  <img
                    src='/assets/images/home/greenmedal.svg'
                    className='img-fluid'
                  />
                </div>
                <div className='col-4'>
                  <img
                    src='/assets/images/home/bluemedal.svg'
                    className='img-fluid'
                  />
                </div>
              </div>
              <div className='row'>
                <div className='col-12 text-center'>
                  <Typography
                    sx={{
                      color: '#696969',
                      fontSize: {
                        xs: '11px',
                        md: '14px',
                      },
                      marginTop: {
                        xs: '15px',
                        md: '35px',
                      },
                      fontFamily: 'Montserrat',
                      lineHeight: '17px',
                      fontWeight: '700',
                    }}
                  >
                    Medali pencapaian yang dapat Anda gunakan untuk kampanye
                    pemasaran
                  </Typography>
                </div>
              </div>
            </div>
          </Box>
        </section>
        {/* </AppFadeIn> */}
        {/* =================================== */}
        {/* <AppFadeInLeft> */}
        <section id='BoxBannerSatuPlatform'>
          <img
            src='/assets/images/home/bannerBoxIklan.svg'
            className='img-fluid'
            style={{width: '100%'}}
          />
        </section>
        {/* </AppFadeInLeft> */}
        {/* =================================== */}
        {/* <AppFadeIn> */}
        <Box
          sx={{
            padding: {
              xs: '20px 0px',
              md: '50px 0px',
            },
          }}
        >
          <div className='container '>
            <div className='row '>
              <Box
                sx={{
                  display: {
                    xs: 'none',
                    md: 'inline',
                  },
                }}
                className='col-xs-12 col-lg-6 text-center'
              >
                <div className={'row '}>
                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={`${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/lingkungan.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Lingkungan
                      </Typography>
                    </div>
                  </div>
                  <div
                    className={`col-6 text-center`}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={` ${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/kerjadanham.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Tenaga Kerja & HAM
                      </Typography>
                    </div>
                  </div>
                </div>
                <div className={'row '}>
                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={`${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/etika.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Etika
                      </Typography>
                    </div>
                  </div>
                  <div
                    className={`col-6 text-center`}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={` ${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/rantai.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Rantai Suplai
                      </Typography>
                    </div>
                  </div>
                </div>
              </Box>
              <Box
                sx={{
                  display: {
                    md: 'none',
                    lg: 'none',
                  },
                  padding: '0px 50px',
                  marginTop: '10px',
                }}
                className='col-xs-12 col-lg-6 text-center'
              >
                <div className={'row no-gutter gx-1 gy-1 '}>
                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={` ${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/rantai.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Rantai Suplai
                      </Typography>
                    </div>
                  </div>
                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={`${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/etika.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Etika
                      </Typography>
                    </div>
                  </div>

                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={` ${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/rantai.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Rantai Suplai
                      </Typography>
                    </div>
                  </div>
                  <div
                    className={`col-6 text-center `}
                    style={{display: 'flex', flexWrap: 'wrap'}}
                  >
                    <div className={`${styles.boxIconMetodology} `}>
                      <img src='/assets/images/home/etika.svg'></img>
                      <Typography
                        sx={{
                          color: (theme) => theme.palette.primary.main,
                          fontSize: {xs: '10px', md: '18px'},
                          fontWeight: '600',
                          lineHeight: {xs: '17px', md: '25px'},
                          fontFamily: 'Montserrat',
                        }}
                      >
                        Etika
                      </Typography>
                    </div>
                  </div>
                </div>
              </Box>
              <div
                className='col-lg-6 col-xs-12 text-center'
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'center',

                  justifyContent: 'center',
                }}
              >
                <Typography
                  sx={{
                    color: (theme) => theme.palette.primary.main,
                    fontSize: '18px',
                    fontWeight: '600',
                    lineHeight: '25px',
                    fontFamily: 'Montserrat',
                    marginTop: {xs: '35px', md: '0px'},
                  }}
                >
                  Metodologi & Acuan Penilaian
                </Typography>
                <Typography
                  sx={{
                    color: (theme) => theme.palette.primary.secondary,
                    fontSize: '14px',
                    fontWeight: '400',
                    lineHeight: '25px',
                    fontFamily: 'Montserrat',
                    marginTop: {xs: '15px', md: '30px'},
                    padding: {xs: '0px 28px', md: '0px 58px'},
                  }}
                >
                  Metodologi penilaian Satuplatform mengacu pada standar
                  nasional dan internasional seperti{' '}
                  <i>
                    Global Reporting Index (GRI), ISO 26000, International
                    Labour Organization (ILO),
                  </i>{' '}
                  dan Program Penilaian Peringkat Kinerja Perusahaan dalam
                  Pengelolaan Lingkungan (PROPER) yang kemudian dikelompokan
                  menjadi 4 tema penilaian yakni Lingkungan, Tenaga Kerja & Hak
                  Asasi Manusia, Etika, dan Rantai Suplai.
                </Typography>
              </div>
            </div>
          </div>
        </Box>
        {/* </AppFadeIn> */}
        {/* =================================== */}
        <Box
          sx={{
            backgroundColor: '#F6F8FA',
            padding: {xs: '10px 0px', md: '60px 0px'},
            boxShadow: '0px 4px 4px rgba(0, 0, 0, 0.25)',
            marginBottom: '4px',
          }}
        >
          {' '}
          <div className='container  '>
            <div className='row'>
              <div className='col-12 text-center'>
                <Typography
                  sx={{
                    color: '#696969',
                    fontSize: {
                      xs: '13px',
                      md: '20px',
                    },
                    lineHeight: '25px',
                    fontFamily: 'Montserrat',
                    fontWeight: '600',
                  }}
                >
                  Mengapa Satuplatform?
                </Typography>
              </div>
            </div>
          </div>
          <div className='container'>
            <Box
              sx={{
                padding: {xs: '20px 40px 20px 40px', md: '60px 0px 30px 0px'},
              }}
              className='row  text-center g-xs-5 g-lg-4 gy-4'
            >
              <Box sx={{}} className={`col-lg-4  ${styles.boxWhy}`}>
                <div className={` ${styles.boxPadding}`}>
                  <img
                    src='/assets/images/home/jaringan.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '16px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '600',
                      lineHeight: {xs: '14px', md: '19px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Bangun Jaringan Bisnis yang Berkelanjutan dan Ramah
                    Lingkungan
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '400',
                      lineHeight: {xs: '14px', md: '17px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Evaluasi aspek lingkungan, sosial, dan etika pada jaringan
                    bisnis Anda dari hulu ke hilir sehingga Anda dapat
                    mewujudkan rantai suplai yang berkelanjutan dan ramah
                    lingkungan
                  </Typography>
                </div>
              </Box>
              <div className={`col-lg-4  ${styles.boxWhy}`}>
                <div className={` ${styles.boxPadding}`}>
                  <img
                    src='/assets/images/home/brand_responsibility.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '16px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '600',
                      lineHeight: {xs: '14px', md: '19px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Menjadi Brand yang Bertanggung Jawab
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '400',
                      lineHeight: {xs: '14px', md: '17px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Tingkatkan reputasi bisnis Anda sebagai bisnis yang
                    bertanggung jawab dan jadikan brand Anda sebagai standar di
                    industri Anda
                  </Typography>
                </div>
              </div>
              <div className={`col-lg-4  ${styles.boxWhy}`}>
                <div className={` ${styles.boxPadding}`}>
                  <img
                    src='/assets/images/home/clock_money.svg'
                    className='img-fluid'
                  />
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '16px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '600',
                      lineHeight: {xs: '14px', md: '19px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Hemat Biaya dan Waktu serta Kurangi Resiko
                  </Typography>
                  <Typography
                    sx={{
                      fontSize: {xs: '12px', md: '14px'},
                      color: (theme) => theme.palette.secondary.main,
                      fontWeight: '400',
                      lineHeight: {xs: '14px', md: '17px'},
                      marginTop: {xs: '20px', md: '40px'},
                    }}
                  >
                    Proses audit Satuplatform dapat membantu bisnis Anda
                    menghemat waktu dan biaya serta mengurangi risiko kerugian &
                    dampak lingkungan yang dapat terjadi
                  </Typography>
                </div>
              </div>
            </Box>
          </div>
        </Box>
        {/* =================================== */}
        <Box
          sx={{
            paddingTop: {xs: '10px', md: '60px'},
            minHeight: {xs: '115px', md: '415px'},
          }}
          className={`${styles.bgBisnis}`}
        >
          <Box className='container ' sx={{padding: {xs: '5px 5px'}}}>
            <div className={`row `}>
              <div className='col-12 text-center'>
                <Typography
                  sx={{
                    color: '#4B4B4C',
                    fontSize: {
                      xs: '13px',
                      md: '20px',
                    },
                    lineHeight: {xs: '21px', md: '25px'},
                    fontFamily: 'Montserrat',
                    fontWeight: '600',
                    marginBottom: {xs: '10px', md: '35px'},
                  }}
                >
                  Siap untuk mewujudkan bisnis <br /> yang bertanggung jawab ?
                </Typography>
              </div>
            </div>
            <div className={`row ${styles['no_gutter']}`}>
              <div className={`col-6 text-center ${styles['no_gutter']}`}>
                <Button
                  sx={{
                    backgroundColor: (theme) => theme.palette.primary.main,
                    marginTop: {xs: '5px', md: '25px'},
                    width: {xs: '100%', md: '90%'},
                    fontSize: {xs: '10px', md: '16px'},
                    lineHeight: {xs: '14px', md: '19px'},
                    fontFamily: 'Montserrat',
                    fontWeight: '700',
                    borderRadius: '40px',
                    padding: {
                      xs: '5px 5px 5px 5px',
                      md: '20px 20px 20px 20px',
                    },
                    marginBottom: {
                      xs: '10px ',
                      md: '20px',
                    },
                  }}
                  variant='contained'
                >
                  Penilaian untuk Bisnis Anda
                </Button>
              </div>
              <div className='col-6 text-center'>
                <Button
                  sx={{
                    backgroundColor: (theme) => theme.palette.primary.main,
                    marginTop: {xs: '5px', md: '25px'},
                    fontSize: '11px',
                    width: {xs: '100%', md: '90%'},
                    fontSize: {xs: '10px', md: '16px'},
                    lineHeight: {xs: '14px', md: '19px'},
                    fontFamily: 'Montserrat',
                    fontWeight: '700',
                    borderRadius: '40px',
                    padding: {
                      xs: '5px 5px 5px 5px',
                      md: '20px 20px 20px 20px',
                    },
                  }}
                  variant='contained'
                >
                  Penilaian untuk Supplier Anda
                </Button>
              </div>
              <div className='col-6 text-center'>
                <Button
                  sx={{
                    marginTop: {xs: '5px', md: '25px'},
                    width: {xs: '100%', md: '90%'},
                    fontSize: {xs: '10px', md: '16px'},
                    lineHeight: {xs: '14px', md: '19px'},
                    fontFamily: 'Montserrat',
                    fontWeight: '700',
                    borderRadius: '40px',
                    padding: {
                      xs: '5px 5px 5px 5px',
                      md: '20px 20px 20px 20px',
                    },
                    backgroundColor: (theme) => theme.palette.primary.main,
                  }}
                  variant='contained'
                >
                  Konsultasi Gratis
                </Button>
              </div>
              <div className='col-6 text-center'>
                <Button
                  sx={{
                    backgroundColor: (theme) => theme.palette.primary.main,
                    marginTop: {xs: '5px', md: '25px'},
                    fontSize: {xs: '10px', md: '16px'},
                    lineHeight: {xs: '14px', md: '19px'},
                    width: {xs: '100%', md: '90%'},
                    fontFamily: 'Montserrat',
                    fontWeight: '700',
                    borderRadius: '40px',
                    padding: {
                      xs: '5px 5px 5px 5px',
                      md: '20px 20px 20px 20px',
                    },
                  }}
                  variant='contained'
                >
                  Ajukan Demo
                </Button>
              </div>
            </div>
          </Box>
        </Box>
      </Layout>
    </>
  );
}
